apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nest-api-monitor
  labels:
    release: kps
spec:
  selector:
    matchLabels:
      app: nest-api
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
  namespaceSelector:
    matchNames:
      - default
