name: CI/CD with image tagging and ArgoCD sync

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: ghcr.io/valentin1982/devops-test

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get short SHA
        id: vars
        run: echo "sha_tag=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"

      - name: Build & Push Docker image with cache
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.sha_tag }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Install yq
        run: |
          sudo snap install yq

      - name: Update image tag and annotation in deployment.yaml
        run: |
          sed -i "s|image: $IMAGE_NAME:.*|image: $IMAGE_NAME:${{ steps.vars.outputs.sha_tag }}|" ./k8s/deployment.yaml
          yq e -i '.spec.template.metadata.annotations."image-tag-updated-at" = "${{ steps.vars.outputs.sha_tag }}"' ./k8s/deployment.yaml

      - name: Commit and push updated deployment.yaml
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add ./k8s/deployment.yaml
          git commit -m "Update image tag to ${{ steps.vars.outputs.sha_tag }}"
          git push
